create database BD_PRUEBA
GO
USE BD_PRUEBA
GO
CREATE TABLE TBL_CATEGORIA
(ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(100) NOT NULL,
ESTADO BIT NOT NULL)
GO
CREATE TABLE TB_PRODUCTOS
(ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
MARCA VARCHAR(100),
DESCRIPCION VARCHAR(100) NOT NULL,
ESTADO BIT NOT NULL,
ID_CATEGORIA INT,
FOREIGN KEY(ID_CATEGORIA) REFERENCES TBL_CATEGORIA(ID_CATEGORIA)
)
